version: '3'

services:
  wordpress:
    image: 'wordpress:${WP_VERSION:-6.1.0}-php${PHP_VERSION:-8.0}-apache'
    environment:
      VIRTUAL_HOST: 'axeptio-wordpress-plugin.test'
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    env_file:
      - .env
    depends_on:
      - 'mysql'
    networks:
      - 'front'
      - 'back'
    volumes:
      - 'wp:/var/www/html:rw'
      - './axeptio-wordpress-plugin:/var/www/html/wp-content/plugins/axeptio-wordpress-plugin:ro'
  wp-cli:
    image: 'wordpress:cli-${WP_CLI_VERSION:-2.7.1}-php${PHP_VERSION:-8.0}'
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    env_file:
      - .env
    depends_on:
      - 'mysql'
    networks:
      - 'back'
    volumes:
      - 'wp:/var/www/html:rw'
      - './bin/install-wp.sh:/usr/local/bin/install-wp:ro'
      - './axeptio-wordpress-plugin:/var/www/html/wp-content/plugins/axeptio-wordpress-plugin:ro'
  mysql:
    image: 'mariadb:10.2'
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - 'back'
  proxy:
    image: 'jwilder/nginx-proxy:alpine'
    ports:
      - '80:80'
    networks:
      front:
        aliases:
          - 'axeptio-wordpress-plugin.test'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

networks:
  front: {}
  back: {}

volumes:
  wp: {}
