name: Auto-Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: auto-release-${{ github.repository }}
  cancel-in-progress: false

jobs:
  auto-release:
    uses: axeptio/tech-scripts/.github/workflows/auto-release.yml@auto-release-v0.0.1
    with:
      target_branch: master
      source_branch: develop
    secrets:
      BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      BOT_GPG_PRIVATE_KEY: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
      BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
