name: Deploy and Release Plugin
on:
  push:
    tags:
    - "*"

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node dependencies
      run: yarn install

    - name: Run ESLint check
      run: yarn eslint

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHPCS check
      run: composer run phpcs

    - name: Run unit tests
      run: vendor/bin/pest

    - name: Build
      run: |
        yarn build:production
        composer install --no-dev --optimize-autoloader
        rsync -av --exclude='tmp' --exclude-from='exclusions.txt' ./ ./tmp/

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: axeptio-sdk-integration

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}